python cifar10_SR_master.py --weight1 1 --weight2 0     --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD00
python cifar10_SR_master.py --weight1 1 --weight2 0.01  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD01
python cifar10_SR_master.py --weight1 1 --weight2 0.02  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD02
python cifar10_SR_master.py --weight1 1 --weight2 0.03  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD03
python cifar10_SR_master.py --weight1 1 --weight2 0.04  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD04
python cifar10_SR_master.py --weight1 1 --weight2 0.05  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD05
python cifar10_SR_master.py --weight1 1 --weight2 0.06  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD06
python cifar10_SR_master.py --weight1 1 --weight2 0.07  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD07
python cifar10_SR_master.py --weight1 1 --weight2 0.08  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD08
python cifar10_SR_master.py --weight1 1 --weight2 0.09  --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD09
python cifar10_SR_master.py --weight1 1 --weight2 0.1   --weight3 0.02 --outdir /media/alan/SteinsGate/github_code/mnist/TensorFlow_WGAN/Cifar10/samples/CPD10